services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/dev_db
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    environment:
      POSTGRES_DB: dev_db # Database name for development

networks:
  backend:
    external: true
